[package]
name = "crow"
version = "0.1.0"
edition = "2021"

[dependencies]
graphql = { path = "../graphql" }
honeybadger = { path = "../honeybadger" }
isocountry = { version = "0.3.2" }
isolanguage-1 = { version = "0.2.2" }

[dev-dependencies]
bitcoin = { version = "0.30.1" }
