[package]
name = "crow"
version = "0.1.0"
edition = "2021"

[dependencies]
graphql = { path = "../graphql" }
honey-badger = { path = "../honey-badger" }

[dev-dependencies]
bitcoin = { version = "0.29.2" }
