name: Build and Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - develop
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
      - name: Checkout
        uses: actions/checkout@v3
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.2.0
      - name: Build honey-badger
        run: cargo build --manifest-path honey-badger/Cargo.toml --verbose
      - name: Run unit tests
        run: make -C honey-badger test
      - name: Set environment variables
        run: echo "GRAPHQL_API_URL=${{ secrets.GRAPHQL_API_URL }}" >> $GITHUB_ENV
      - name: Run integration tests
        run: make -C honey-badger integrationtests
