name: Static code analysis

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '21 2 * * 1-5' # every weekday at 2:21 AM UTC

jobs:
  security-audit:
    name: Security audit
    runs-on: ubuntu-latest
    steps:
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
      - name: Install security audit
        run: cargo install cargo-audit
      - uses: actions/checkout@v3
      - name: Run security audit
        run: cargo audit
  fmt_check:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          components: rustfmt
      - uses: actions/checkout@v3
      - name: Check code formatting
        run: make fmt-check
  clippy_check:
    name: Clippy check
    runs-on: ubuntu-latest
    steps:
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          components: clippy
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Clippy
        run: make clippy check-version
  linelint:
    name: Check that files end with line break
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Linelint
        uses: fernandrone/linelint@master
        id: linelint  
  unused_dependencies:
    name: Look for unused dependencies
    runs-on: ubuntu-latest
    steps:
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly-2023-12-28
          override: true
      - name: Install unused dependency checker
        run: cargo install cargo-udeps --locked
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run unused dependency checker
        run: cargo +nightly-2023-12-28 udeps
